version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    command: npm run start:prod
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/testdb
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db_data:
